on:
  delete:
    branches-ignore:
      - qa
      - main
      - master

name: DeleteEnv

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cleanup Feature K8S Env
      run: |
        export REF=$(echo "${{ github.event.ref }}" | sed -e "s#refs/heads/##g")
        sh scripts/prune.sh --heavy
